version: '2'
services:
  word-microservice:
    image: sysunite/word-microservice:1.0.3
    mem_limit: 3096m
    restart: on-failure
    expose:
      - "9268"
    ports:
      - "9268:9268"
    volumes:
      - './volumes/word-microservice/files:/usr/src/app/files'
      - './volumes/word-microservice/filesTmp:/usr/src/app/filesTmp'
