// Generated by CoffeeScript 1.12.4
(function() {
  var Console, Logger, config, formatter, logger, moment, timestamp, transports, winston;

  require('colors');

  winston = require('winston');

  moment = require('moment');

  config = require('config');

  timestamp = function() {
    return moment().format("YYYY-MM-DD HH:mm:ss");
  };

  formatter = function(options) {
    var level, message, object, time, total;
    time = options.timestamp();
    level = options.level.toUpperCase();
    message = options.message != null ? options.message : '';
    object = (options.meta != null) && Object.keys(options.meta).length !== 0 ? '\n\t' + JSON.stringify(options.meta) : '';
    total = time + " | " + level + " | " + message + " " + object;
    if (level === 'ERROR') {
      total = total.red;
    }
    total;
    if (level === 'DEBUG') {
      total = total.cyan;
    }
    total;
    if (level === 'WARN') {
      total = total.yellow;
    }
    total;
    if (level === 'INFO') {
      total = total.green;
    }
    return total;
  };

  Console = winston.transports.Console;

  transports = [
    new Console({
      timestamp: timestamp,
      formatter: formatter
    })
  ];

  Logger = winston.Logger;

  logger = new Logger({
    transports: transports
  });

  logger.level = "" + (config.get('logging.console'));

  module.exports = logger;

}).call(this);
